### PR TITLE
Fix line endings

### PR DESCRIPTION
**Pull request by Megasware128**
Everytime I try to edit a file, git gets confused about the line endings. So I added a gitattributes file which should fix this.

### CODE REVIEW

**Comment by ferventcoder** [comment]
Hello @Megasware128 - what line endings did it have before? If it is not already using core.crlf=false, I will be changing it to that once I start contributing to this repository.

**Comment by Megasware128** [comment]
According to the `file` utility from *nix it seems it was CRLF. Used Git Bash which was included with msysgit.

**Comment by ferventcoder** [comment]
In the repo, type `git config core.autocrlf false` Ensure this is in the repository.

**Comment by ferventcoder** [comment]
This won't set your system configuration, you would need `--global` to make that change.

**Comment by Megasware128** [comment]
Ah okay. Thank you. That works 👍

**Pull request closed without merging**
